# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  marvel: scoperetail/marvel@dev:374ba8b

workflows:
  build-and-test:
    jobs:
      - marvel/maven-deploy:
          context:
            - OSSRH
            - SLACK
          filters:
            branches:
              ignore:
                - master
                - /HOTFIX-.*/
      - marvel/maven-release:
          context:
            - OSSRH
            - SLACK
          filters:
            branches:
              only:
                - master
                - /HOTFIX-.*/